# Memory Optimization (Windows için 4G en stabil değerdir)
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC

# Parallel Execution & Caching
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true

# AndroidX and Kotlin Flags
android.useAndroidX=true
android.enableJetifier=false
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
